### ISSUE TITLE
Building from makefile

### ISSUE THREAD

**Issue by NotErista** [Team-Neptune/DeepSea-Toolbox#1]
hi iam having troble building from makefile it says i have the wrong cygwin1.dll version

**Comment by Slluxx** [comment]
Then its probably not an issue with our repo. Can you build other hbs? Are you actually using cygwin? The devkit way would be msys2 instead of cygwin. can you tell us more about your setup?

**Comment by YourAvarageMailman** [comment]
Iam using Cygwin and i have uninstalled it and reinstalled it many times
and i have tried Reinstalling devkit as well

**Comment by YourAvarageMailman** [comment]
THis is the full error.

$ make
      0 [main] make (78396) C:\devkitPro\msys2\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x18034C408/0x180345408.
                                                            This problem is probably due to using incompatible versions of the cygwin DLL.
                                                          Search for cygwin1.dll using the Windows Start->Find/Search facility
                                              and delete all but the most recent version.  The most recent version *should*
                                           reside in x:\cygwin\bin, where 'x' is the drive on which you have
                            installed the cygwin distribution.  Rebooting is also suggested if you
                  are unable to find another cygwin DLL.

**Comment by Slluxx** [comment]
and have you tried what is beeing suggested to you?

i am sorry but this has nothing to do with our toolbox so we cant give you any more assistance than suggesting to google the error

**Comment by NotErista** [comment]
Hey so i uninstalled every thing but i have forgotten how to install make 
. could you guide me

**Comment by Slluxx** [comment]
No, sorry. Please read some tutorials on how to get set up.

**Comment by Slluxx** [comment]
And next time please be at least honest about your identity. We know you wanted to do your own thing but blatantly copying others work, cloning their repos and trying to modify just a single thing isnt really good practice. There is alot of work in this and it requires some coding knowlege. If you are interested in learning homebrew development or anything, you are still welcome in our discord to get the help you need or require. But just be fucking honest with us.

**Comment by NotErista** [comment]
Sorry about that but iam over with all of it because now I look back it
seemed pointless

**Comment by NotErista** [comment]
And iam banned from Your server but I have never joined
